In [16]:
import numpy as np
def fixed_point_map(feature,subset,subcheck):
        dim=len(feature[1])
        number=len(feature[:,1])
        feature=feature.reshape(number,dim)
        eta=.25
        exceptions=[]
#         W=np.random.rand(dim,dim)
        W = np.array([[1]*dim]*dim).astype(float)
        Z = np.array([[0]*number]*number).astype(float)
        I = np.array([[0]*number]*number)
        for i in range(number):
            for j in range(number):
                if(i==j):
                    I[i][j]=1
                            
        subsetf=[]
        for i in subset:
            a=[]
            if(i[0]!=i[1]):
                for j in range(i[0],i[1]+1):
                    a.append(j)
                subsetf.append(a)
          
        L=np.matmul(np.matmul(feature,W),feature.transpose())
        

        for i in range(100):
            for k in range (len(subsetf)):
                sub=subsetf[k]
                ly=[]
                for i in sub:
                    a=[]
                    for j in sub:
                        a.append(L[i][j])
                    ly.append(a)
                try:  
                    ly=np.array(ly)
                    lyinv=np.linalg.inv(ly)
            
                    b=[]
                    for i in range (len(sub)):
                        for j in range (len(sub)):
                              b.append(lyinv[i][j])
                    start=0
                    stop=1

                    for i in sub:
                        for j in sub:
                            for k in range(start,stop):
                                Z[i][j]=Z[i][j]+b[k]
                                start=start+1
                                stop=stop+1
                                break
                except:
                    exceptions.append(k)
            Z=Z/len(subsetf)  
            e=np.matmul(feature.transpose(),np.matmul(Z-np.linalg.inv(L+I),feature))
            W=W+np.matmul(eta*(W),((np.matmul(e,W))))
            L=np.matmul(np.matmul(feature,W),feature.transpose())
        probab=[]
        
        for k in range (len(subsetf)):
            sub=subsetf[k]
            ly=[]
            for i in sub:
                a=[]
                for j in sub:
                    a.append(L[i][j])
                ly.append(a)
            ly=np.array(ly)
            probab.append((np.linalg.det(ly)/np.linalg.det(L+I)))
        
        checkprobab=[]    
        
        for k in range (len(subcheck)):
            sub=subcheck[k]
            ly=[]
            for i in sub:
                a=[]
                for j in sub:
                    a.append(L[i][j])
                ly.append(a)
            ly=np.array(ly)
            checkprobab.append((np.linalg.det(ly)/np.linalg.det(L+I))) 
        
        return L,exceptions,probab,checkprobab
feature=np.load("/home/her/DPPFAQ/featurefaq.npy")
subset=np.load("/home/her/DPPFAQ/subsetfaq.npy")
subcheck=[[0,3],[3,7],[7,9],[9,11],[11,12],[12],[13],[12,13],[60,61,62,63,64]]
L,exceptions,probab,checkprobab=fixed_point_map(feature,subset,subcheck)

In [17]:
subset

array([[ 0,  2],
       [ 3,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 15],
       [16, 21],
       [22, 25],
       [26, 28],
       [29, 32],
       [33, 34],
       [35, 37],
       [38, 41],
       [42, 45],
       [46, 47],
       [48, 49],
       [50, 52],
       [53, 59],
       [60, 63],
       [64, 65],
       [66, 70],
       [71, 73],
       [74, 78],
       [79, 80],
       [81, 84],
       [85, 88],
       [89, 92],
       [93, 94],
       [95, 98]])

In [18]:
np.absolute(probab)

array([1.00655422e-038, 0.00000000e+000, 1.25559741e-021, 4.86436947e-020,
       1.40077823e-019, 2.45723918e-038, 3.72082829e-096, 1.57339551e-059,
       9.35508728e-040, 1.03658779e-057, 3.86401880e-020, 5.04864591e-040,
       3.03645045e-058, 5.77463923e-062, 4.25839208e-022, 1.33762449e-019,
       8.77301614e-039, 9.64988410e-115, 1.27462561e-059, 3.63402226e-020,
       1.34008453e-078, 9.21059924e-040, 2.47096834e-080, 3.78544822e-020,
       2.04836754e-060, 2.17882132e-060, 1.28722776e-058, 2.23349450e-020,
       1.52706654e-059])

In [3]:
np.save("/home/her/DPPFAQ/Lad.npy", L)

In [4]:
import numpy as np
L=np.load("/home/her/DPPFAQ/L.npy")

In [31]:
import numpy as np
f = open('/home/her/DPP/project.txt', 'r')
x= f.read().splitlines()
f.close()
x1=" ".join(x)
x1=x1.split('.')
sent=[]
counter=[]
a=0
for i in range(len(x1)):
    d=[]
    d.append(x1[i].split('?'))
    d=sum(d,[])
    if(len(d)>1):
        counter.append(i+a)
        a=a+1
    sent.append(list(d))
x=sum(sent,[])

subset=np.load("/home/her/DPP/subsetfaq.npy")
subset
f=[]
xclean=np.load("/home/her/DPP/subsetfaqcleaned.npy")

for i in range (len(probab)):
    g=[]
    for j in range (len(probab)):
        if(np.absolute(np.round(probab[i],100)-np.round(probab[j],100))==0 ):
            g.append(j)
    if g not in f:
        f.append(g)
# print(f)
final=[]
for i in f:
    final1=[]
    for j in i:
            o=subset[j]
#             print(subset[j])
            p=o[0]
            q=o[1]+1
#             print(p,q)
            final1.append(x[p:q])
    final.append(final1)

len(final)

28

In [28]:
f

[[0],
 [1, 17],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24],
 [25],
 [26],
 [27],
 [28]]

In [25]:
for l in subset[:,0]:
    subcheck=[l,10]
    checkprobab=[]    
        
    number =99
    I = np.array([[0]*number]*number)
    for i in range(number):
        for j in range(number):
            if(i==j):
                I[i][j]=1
                    
    for k in range (len(subcheck)):
        sub=subcheck
        ly=[]
        for i in sub:
            a=[]
            for j in sub:
                a.append(L[i][j])
            ly.append(a)
        ly=np.array(ly)
    checkprobab.append((np.linalg.det(ly)/np.linalg.det(L+I))) 
    print(np.absolute(checkprobab))
        

[8.49097893e-20]
[5.3754097e-21]
[4.50606131e-20]
[4.86436947e-20]
[1.12120292e-20]
[7.59364875e-21]
[1.2794594e-20]
[3.97714332e-21]
[4.62109769e-20]
[5.2392814e-20]
[3.04723687e-20]
[1.76158847e-19]
[3.25521077e-21]
[6.56178635e-21]
[9.94719188e-22]
[1.30537212e-19]
[9.07414385e-21]
[1.10729292e-19]
[3.97714332e-21]
[9.00119031e-21]
[1.21331675e-20]
[1.27011225e-20]
[9.89276031e-21]
[1.70691782e-20]
[2.40433073e-20]
[1.65891033e-20]
[2.02567181e-20]
[7.15447876e-20]
[1.88728702e-21]


In [147]:
# checkprobab=np.round(checkprobab)
np.absolute(checkprobab)

array([1.74150746, 0.00177056, 0.14363998, 0.05998311, 0.13569296,
       0.03930645, 0.00763306, 1.14411951, 0.06658781])

In [118]:
import numpy as np
def fixed_point_map(feature,subset,subcheck):
        dim=len(feature[1])
        number=len(feature[:,1])
        feature=feature.reshape(number,dim)
        eta=.25
        exceptions=[]
        W=np.random.rand(dim,dim)
        Z = np.array([[0]*number]*number).astype(float)
        I = np.array([[0]*number]*number)
        for i in range(number):
            for j in range(number):
                if(i==j):
                    I[i][j]=1
                            
        subsetf=[]
        for i in subset:
            a=[]
            if(i[0]!=i[1]):
                for j in range(i[0],i[1]+1):
                    a.append(j)
                subsetf.append(a)
            
        L=np.matmul(np.matmul(feature,W),feature.transpose())

        for i in range(500):
            for k in range (len(subsetf)):
                sub=subsetf[k]
                ly=[]
                for i in sub:
                    a=[]
                    for j in sub:
                        a.append(L[i][j])
                    ly.append(a)
                try:  
                    ly=np.array(ly)
                    lyinv=np.linalg.inv(ly)
            
                    b=[]
                    for i in range (len(sub)):
                        for j in range (len(sub)):
                              b.append(lyinv[i][j])
                    start=0
                    stop=1

                    for i in sub:
                        for j in sub:
                            for k in range(start,stop):
                                Z[i][j]=Z[i][j]+b[k]
                                start=start+1
                                stop=stop+1
                                break
                except:
                    exceptions.append(k)
            Z=Z/len(subsetf)        
            L=L+np.matmul(eta*(L),((Z-np.matmul(np.linalg.inv(L+I),L))))
        
        probab=[]
        
        for k in range (len(subsetf)):
            sub=subsetf[k]
            ly=[]
            for i in sub:
                a=[]
                for j in sub:
                    a.append(L[i][j])
                ly.append(a)
            ly=np.array(ly)
            probab.append(10**10*(np.linalg.det(ly)/np.linalg.det(L+I)))
        
        checkprobab=[]    
        
        for k in range (len(subcheck)):
            sub=subcheck[k]
            ly=[]
            for i in sub:
                a=[]
                for j in sub:
                    a.append(L[i][j])
                ly.append(a)
            ly=np.array(ly)
            checkprobab.append(10**10*(np.linalg.det(ly)/np.linalg.det(L+I))) 
        
        return L,exceptions,probab,checkprobab
feature=np.load("/home/her/DPPFAQ/featurefaq.npy")
subset=np.load("/home/her/DPPFAQ/subsetfaq.npy")
subcheck=[[0,3],[3,7],[7,9],[9,11],[11,12],[12],[13],[12,13],[60,61,62,63,64]]
L,exceptions,probab,checkprobab=fixed_point_map(feature,subset,subcheck)