In [1]:
f = open('/home/her/DPP/notebook.txt', 'r')
x= f.read().splitlines()
f.close()

In [68]:
""""
from gensim.parsing.preprocessing import strip_punctuation,strip_numeric
y=strip_punctuation(x[1])
g=[]
for i in range(len(x)):
    a=strip_punctuation(x[i])
    a=strip_numeric(a)
    g.append(a)    
g[:20]
f=[]
for i in g:
#     print(len(i))
    if(len(i)!=0):
        f.append(i)
f[:10]
""""

['         ',
 'Excuse me ',
 '         ',
 'Come on  honey  let s',
 'get you ready for bed ',
 '         ',
 'I am no one special ',
 '         ',
 'just a common man',
 'with common thoughts ']

#### REMOVING SPECIAL CHARACTERS

In [2]:
d =[]
elim=['1','2','3','4','5','6','7','8','9','0',':',';','>','<','/',',','-','\\','#']
for i in x:
    sent = " ".join("".join(["" if ch in elim else ch for ch in i]).split())
    d.append(sent)

In [4]:
f=[]
for i in d:
#     print(len(i))
    if(len(i)!=0):
        f.append(i)
f[:5]
len(f)

2664

In [4]:
fin=" ".join(f)
k=fin.split('.')
k[:5]

['Excuse me',
 " Come on honey let's get you ready for bed",
 ' I am no one special just a common man with common thoughts',
 " I've led a common life",
 ' There are no monuments dedicated to me']

In [5]:
fin1=[]
for i in k:
    fin1.append(i.split("?"))
fin1[:5]

[['Excuse me'],
 [" Come on honey let's get you ready for bed"],
 [' I am no one special just a common man with common thoughts'],
 [" I've led a common life"],
 [' There are no monuments dedicated to me']]

####  CONVERT 2D LIST TO 1D 

In [6]:
fin1=sum(fin1,[])
len(fin1)
fin1[38]

''

#### SUBSET GROUPING

In [7]:
samplebound=[]
for i in range(len(fin1)):
    if(len(fin1[i])==0):
          samplebound.append(i)

In [8]:
samplebound[:10]

[31, 32, 38, 39, 78, 79, 86, 87, 89, 90]

In [9]:
import numpy as np
bound=[]
bound.append([0,samplebound[0]-1])

for i in range(len(samplebound)-1):
    if ((samplebound[i+1]-samplebound[i])>1):
        a=[]
        a.append(samplebound[i]+1)
        a.append(samplebound[i+1]-1)
        bound.append(a) 
subset=np.array(bound)

In [10]:
subset=np.array(subset)
np.save("/home/her/DPP/subset.npy", subset)
subset[:10]

array([[  0,  30],
       [ 33,  37],
       [ 40,  77],
       [ 80,  85],
       [ 88,  88],
       [ 91,  93],
       [ 96, 123],
       [126, 149],
       [152, 162],
       [165, 167]])

#### wordvec

In [11]:
sentences=[]
for i in fin1:
    sentences.append((i).split())

In [12]:
type(sentences)
sentlength=[]
for i in sentences:
    sentlength.append(len(i))
print(max(sentlength))
sentences[:3]

42


[['Excuse', 'me'],
 ['Come', 'on', 'honey', "let's", 'get', 'you', 'ready', 'for', 'bed'],
 ['I',
  'am',
  'no',
  'one',
  'special',
  'just',
  'a',
  'common',
  'man',
  'with',
  'common',
  'thoughts']]

In [13]:
from gensim.models import Word2Vec
model = Word2Vec(sentences,size=3, min_count=1)
print(model)
words = list(model.wv.vocab)
model.save("/home/her/DPP/word2vecsubtitles.model")
# print((words))

Word2Vec(vocab=1620, size=3, alpha=0.025)


#### Feature matrix

In [34]:
zerovector=[]
for i in range(3):
  zerovector.append(.0001)

def sentencevector(sent):
  vector=[]
  for word in sent:
       vector.append(model[word])
  if(len(sent)<max(sentlength)):
    for i in range(len(sent),max(sentlength)):
      vector.append(zerovector)
  return(vector)


feature=[]
for i in range(len(sentences)):
    a=np.array(sentencevector(sentences[i]))
    a=a.reshape(126)
    feature.append(a)
    
features=np.array(feature)

/home/her/bhavya/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [15]:
features[33]

array([ 0.08458272,  0.03219376, -0.28012589,  0.49387267,  0.26729167,
       -0.33954626,  0.46310681,  0.21355279, -0.47127345,  0.09683688,
        0.17596965, -0.26109123,  0.38655928,  0.29287291, -0.23788272,
        0.53056842,  0.52516556, -0.50195867,  0.00121597,  0.26026034,
       -0.02824768,  0.03331288, -0.04094418,  0.05174044,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1 

In [35]:
type(feature)

list

In [36]:
np.save("/home/her/DPP/feature.npy", feature)

In [17]:
subset=np.array(subset)
np.save("/home/her/DPP/subset.npy", subset)
subset[:10]

array([[  0,  30],
       [ 33,  37],
       [ 40,  77],
       [ 80,  85],
       [ 88,  88],
       [ 91,  93],
       [ 96, 123],
       [126, 149],
       [152, 162],
       [165, 167]])

In [37]:
featurefinal=[]
for a in subset:
    featurefinal.append(feature[a[0]:a[1]])
featurefinal=sum(featurefinal,[])
featurefinal=np.array(featurefinal)   
featurefinal

array([[ 1.18045971e-01,  8.89236331e-02, -6.17957748e-02, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04],
       [ 1.52533397e-01,  8.71773809e-02, -3.73135924e-01, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04],
       [ 8.92009795e-01,  7.60515153e-01, -9.70908225e-01, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04],
       ...,
       [ 8.92009795e-01,  7.60515153e-01, -9.70908225e-01, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04],
       [ 8.92009795e-01,  7.60515153e-01, -9.70908225e-01, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04],
       [ 1.35119915e-01,  2.16811635e-02, -7.22260997e-02, ...,
         1.00000000e-04,  1.00000000e-04,  1.00000000e-04]])

In [38]:
np.save("/home/her/DPP/featurefinal.npy", featurefinal)

In [20]:
sublength=[]
for a in subset:
    sublength.append(a[1]-a[0]+1)
    

In [21]:
sublength

[31,
 5,
 38,
 6,
 1,
 3,
 28,
 24,
 11,
 3,
 4,
 13,
 4,
 3,
 2,
 17,
 2,
 8,
 7,
 22,
 23,
 5,
 1,
 1,
 3,
 4,
 1,
 1,
 15,
 7,
 2,
 17,
 34,
 33,
 13,
 1,
 11,
 3,
 1,
 12,
 40,
 1,
 1,
 1,
 1,
 8,
 2,
 20,
 14,
 7,
 8,
 39,
 6,
 1,
 6,
 12,
 7,
 1,
 5,
 13,
 1,
 8,
 2,
 1,
 61,
 5,
 4,
 37,
 9,
 21,
 65,
 18,
 6,
 8,
 7,
 7,
 45,
 13,
 2,
 2,
 6,
 53,
 11,
 25,
 11,
 31,
 28,
 42,
 75,
 5,
 11,
 1,
 26,
 20,
 39,
 1,
 2,
 28,
 13,
 14,
 3,
 13,
 1,
 42,
 18,
 3,
 6,
 37,
 5,
 5,
 38,
 28,
 16,
 3,
 7,
 29,
 3,
 3,
 2,
 4,
 5,
 11,
 5,
 2,
 6,
 1,
 11,
 1,
 7,
 7,
 5,
 62]

In [24]:
fins=[]
a=0
for i in sublength:
    b=[]
    b.append(a)
    a=a+i-1
    b.append(a)   
    fins.append(b)    

In [25]:
fins

[[0, 30],
 [30, 34],
 [34, 71],
 [71, 76],
 [76, 76],
 [76, 78],
 [78, 105],
 [105, 128],
 [128, 138],
 [138, 140],
 [140, 143],
 [143, 155],
 [155, 158],
 [158, 160],
 [160, 161],
 [161, 177],
 [177, 178],
 [178, 185],
 [185, 191],
 [191, 212],
 [212, 234],
 [234, 238],
 [238, 238],
 [238, 238],
 [238, 240],
 [240, 243],
 [243, 243],
 [243, 243],
 [243, 257],
 [257, 263],
 [263, 264],
 [264, 280],
 [280, 313],
 [313, 345],
 [345, 357],
 [357, 357],
 [357, 367],
 [367, 369],
 [369, 369],
 [369, 380],
 [380, 419],
 [419, 419],
 [419, 419],
 [419, 419],
 [419, 419],
 [419, 426],
 [426, 427],
 [427, 446],
 [446, 459],
 [459, 465],
 [465, 472],
 [472, 510],
 [510, 515],
 [515, 515],
 [515, 520],
 [520, 531],
 [531, 537],
 [537, 537],
 [537, 541],
 [541, 553],
 [553, 553],
 [553, 560],
 [560, 561],
 [561, 561],
 [561, 621],
 [621, 625],
 [625, 628],
 [628, 664],
 [664, 672],
 [672, 692],
 [692, 756],
 [756, 773],
 [773, 778],
 [778, 785],
 [785, 791],
 [791, 797],
 [797, 841],
 [841, 853],


In [26]:
np.save("/home/her/DPP/subsetfinal.npy", fins)